[versions]
agp = "8.13.2"
firebaseAppdistribution = "16.0.0-beta17"
firebaseAppdistributionApiKtx = "16.0.0-beta15"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
gms = "4.4.4"
firebase = "34.7.0"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinTest = "2.2.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
uiTextGoogleFonts = "1.10.0"
compose-material-icons-extended = "1.7.8"
nav_version = "2.9.6"
firebaseAuth = "24.0.1"
playServicesAuth = "21.4.0"
koin = "4.1.1"
coil3 = "3.3.0"
ktor = "3.3.3"
credentials = "1.5.0"
googleid = "1.1.1"
crashlytics = "3.0.6"
firebasePerfPlugin = "2.0.2"
uiTestJunit4Android = "1.10.0"
mockk = "1.14.7"
playIntegrity = "1.6.0"
appCheckDebug = "19.0.1"
inappMessaging = "22.0.2"
messaging = "25.0.1"
coroutinesTest = "1.10.2"
kotlinxSerializationJson = "1.9.0"
uiautomator = "2.3.0"
benchmarkMacroJunit4 = "1.4.1"
profileinstaller = "1.4.1"
datastore = "1.2.0"
testManifest = "1.10.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "testManifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-material-icons-extended" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "nav_version" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-appcheck-playintegrity = { group = "com.google.firebase", name = "firebase-appcheck-playintegrity" }
firebase-appcheck-debug = { group = "com.google.firebase", name = "firebase-appcheck-debug", version.ref = "appCheckDebug" }
firebase-crashlytics-ndk = { group = "com.google.firebase", name = "firebase-crashlytics-ndk" }
firebase-perf = { group = "com.google.firebase", name = "firebase-perf" }
firebase-inapp-messaging = { module = "com.google.firebase:firebase-inappmessaging-display", version.ref = "inappMessaging" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "messaging" }
firebase-appdistribution = { module = "com.google.firebase:firebase-appdistribution", version.ref = "firebaseAppdistribution" }
firebase-appdistribution-api-ktx = { module = "com.google.firebase:firebase-appdistribution-api-ktx", version.ref = "firebaseAppdistributionApiKtx" }


mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinTest" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "uiTestJunit4Android" }


play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
play-integrity = { group = "com.google.android.play", name = "integrity", version.ref = "playIntegrity" }
identity-googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }


koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }


coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }


ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = {id = "com.google.gms.google-services", version.ref = "gms" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
android-test = { id = "com.android.test", version.ref = "agp" }

[bundles]

compose = [
    "androidx-activity-compose",
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-material3",
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
    "compose-material-icons-extended",
    "navigation-compose",
    "androidx-credentials",
    "credentials-play-services-auth",
    "identity-googleid",
    "androidx-ui-text-google-fonts",
    "kotlinx-serialization-json",
    "androidx-profileinstaller",
    "androidx-datastore"
]

test = [
    "mockk",
    "junit",
    "kotlin-test",
    "kotlinx-coroutines-test"
]

android-test = [
    "mockk-android",
    "androidx-junit",
    "androidx-espresso-core",
    "androidx-ui-test-junit4-android"
]

compose-debug = [
    "androidx-ui-tooling",
    "androidx-ui-test-manifest",
]

firebase = [
    "firebase-bom",
    "firebase-analytics",
    "firebase-auth",
    "firebase-appcheck-playintegrity",
    "firebase-appcheck-debug",
    "firebase-firestore",
    "play-services-auth",
    "firebase-crashlytics-ndk",
    "firebase-perf",
    "play-integrity",
    "firebase-inapp-messaging",
    "firebase-messaging"
]

koin = [
    "koin-android",
    "koin-androidx-compose",
    "koin-core",
    "koin-compose",
    "koin-compose-viewmodel"
]

coil = [
    "coil-compose",
    "coil-compose-core",
    "coil-network-ktor3",
    "coil-mp"
]

ktor = [
    "ktor-client-core",
    "ktor-client-okhttp"
]
